//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ Compatible
// This file was automatically generated by RisohEditor.
// vista2xp_res.rc

#define IDC_STATIC                          -1

#define IDD_MAIN                            1

#define IDI_MAIN                            1

#define IDS_FILETITLE                       100
#define IDS_FOLDERTITLE                     101
#define IDS_NOITEMS                         102
#define IDS_CANTLOAD                        103
#define IDS_CANTWRITE                       104
#define IDS_LOADV2XKER32                    105
#define IDS_COMPLETE                        106
#define IDS_NOTSUP64BIT                     107
#define IDS_LOADV2XCTL32                    108
#define IDS_LOADV2XU32                      109

#ifdef APSTUDIO_INVOKED
    #ifndef APSTUDIO_READONLY_SYMBOLS
        #define _APS_NO_MFC                 1
        #define _APS_NEXT_RESOURCE_VALUE    100
        #define _APS_NEXT_COMMAND_VALUE     100
        #define _APS_NEXT_CONTROL_VALUE     1000
        #define _APS_NEXT_SYMED_VALUE       300
    #endif
#endif
